name: Build and deploy JAR

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: spring-weather-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK@8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' #OpenJDK
          java-version: 8
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spring-weather-prediction
          path: |
            build/libs/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        run: |
          docker build -t pvkr/string-reply:${{github.ref_name}}-${{github.sha}} -t pvkr/spring-weather-prediction:latest .
          docker push pvkr/string-reply:${{github.ref_name}}-${{github.sha}}
          docker push pvkr/string-reply:latest